version: '3.8'

services:
    backend:
        container_name: node-backend-container
        build: ./backend
        image: backend:dev
        ports:
            - 9103:9103
        expose:
            - 9103
        environment:
            DB_HOST: db
            DB_PORT: '3306'
            DB_USER: 'root'
            DB_PASSWORD: 'rootroot123'
            DB_NAME: 'diode_io'
            DB_CONNECTION_LIMIT: 10
            REDIS_HOST: redis
        volumes:
            - ./backend:/backend
        depends_on:
            - db
            - redis

    db:
        container_name: mysql-container
        image: mariadb:latest
        command: --default-authentication-plugin=mysql_native_password
        restart: unless-stopped
        volumes:
            - ./db:/var/lib/mysql:rw
            - ./database/full_dump.sql:/docker-entrypoint-initdb.d/0_init.sql:ro
        ports:
            - 33060:3306
        expose:
            - 3306
        environment:
            MYSQL_DATABASE: diode_io
            MYSQL_USER: root
            MYSQL_ROOT_PASSWORD: rootroot123

    redis:
        container_name: redis-container
        image: redis:6.2.6
        restart: unless-stopped
        ports:
            - '63790:6379'

    frontend:
        container_name: node-frontend-container
        build: ./frontend
        image: frontend:dev
        ports:
            - 8000:8000
        expose:
            - 8000
        volumes:
            - ./frontend:/frontend
